"""add type column not null default tool

Revision ID: 03ea244985ce
Revises: d57accd375ae
Create Date: 2025-12-16 18:17:12.193877

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03ea244985ce'
down_revision = 'd57accd375ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_recommended_plugins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), server_default=sa.text("'tool'"), nullable=False))

    # ASA custom columns
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('installed_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('asa_uid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('access_scope', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_recommended_plugins', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ASA custom columns
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('access_scope')
        batch_op.drop_column('asa_uid')
        batch_op.drop_column('asa_company_id')

    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.drop_column('asa_company_id')

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('asa_company_id')

    with op.batch_alter_table('installed_apps', schema=None) as batch_op:
        batch_op.drop_column('asa_company_id')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('asa_company_id')
    # ### end Alembic commands ###
