"""add type column not null default tool

Revision ID: 03ea244985ce
Revises: d57accd375ae
Create Date: 2025-12-16 18:17:12.193877

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03ea244985ce'
down_revision = 'd57accd375ae'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add type column to pipeline_recommended_plugins if not exists
    if not column_exists('pipeline_recommended_plugins', 'type'):
        with op.batch_alter_table('pipeline_recommended_plugins', schema=None) as batch_op:
            batch_op.add_column(sa.Column('type', sa.String(length=50), server_default=sa.text("'tool'"), nullable=False))

    # ASA custom columns - check if they exist before adding
    if not column_exists('apps', 'asa_company_id'):
        with op.batch_alter_table('apps', schema=None) as batch_op:
            batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    if not column_exists('installed_apps', 'asa_company_id'):
        with op.batch_alter_table('installed_apps', schema=None) as batch_op:
            batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    if not column_exists('workflows', 'asa_company_id'):
        with op.batch_alter_table('workflows', schema=None) as batch_op:
            batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    if not column_exists('app_model_configs', 'asa_company_id'):
        with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    if not column_exists('datasets', 'asa_company_id'):
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.add_column(sa.Column('asa_company_id', sa.String(length=255), nullable=True))

    if not column_exists('datasets', 'asa_uid'):
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.add_column(sa.Column('asa_uid', sa.String(length=255), nullable=True))

    if not column_exists('datasets', 'access_scope'):
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.add_column(sa.Column('access_scope', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('pipeline_recommended_plugins', 'type'):
        with op.batch_alter_table('pipeline_recommended_plugins', schema=None) as batch_op:
            batch_op.drop_column('type')

    # ASA custom columns - check if they exist before dropping
    if column_exists('datasets', 'access_scope'):
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.drop_column('access_scope')

    if column_exists('datasets', 'asa_uid'):
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.drop_column('asa_uid')

    if column_exists('datasets', 'asa_company_id'):
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.drop_column('asa_company_id')

    if column_exists('app_model_configs', 'asa_company_id'):
        with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
            batch_op.drop_column('asa_company_id')

    if column_exists('workflows', 'asa_company_id'):
        with op.batch_alter_table('workflows', schema=None) as batch_op:
            batch_op.drop_column('asa_company_id')

    if column_exists('installed_apps', 'asa_company_id'):
        with op.batch_alter_table('installed_apps', schema=None) as batch_op:
            batch_op.drop_column('asa_company_id')

    if column_exists('apps', 'asa_company_id'):
        with op.batch_alter_table('apps', schema=None) as batch_op:
            batch_op.drop_column('asa_company_id')
    # ### end Alembic commands ###
